module.exports = {
  DEFAULT_STEP_FUNCTIONS_PORT: 8083,
  DEFAULT_LABMDA_PORT: 3001,
  DEFAULT_REDIS_PORT: 6379,
  LINUX_PLATFORM: 'linux',
  DARWIN_PLATFORM: 'darwin',
  LAMBDA_NAME: 'MockFunction',
  LAMBDA_ARN: 'arn:aws:lambda:us-east-1:123456789012:function:MockFunction',
  DEFAULT_EXECUTION_TIMEOUT: 10000,
  DEFAULT_EXECUTION_INTERVAL: 100
}
