module.exports = {
  DEFAULT_STEP_FUNCTIONS_PORT: 8083,
  DEFAULT_LABMDA_PORT: 3001,
  DEFAULT_REDIS_PORT: 6379,
  LINUX_PLATFORM: 'linux',
  DARWIN_PLATFORM: 'darwin',
  LAMBDA_NAME: 'MockFunction'
}
